export {
  createJmapServer,
  type JmapServer,
  type JmapServerOptions,
} from './lib/server.js';
// The parts, for those who use the server as it comes and need their types.
export {
  ConflictError,
  DEFAULT_LIMITS,
  isPublicHttpsUrl,
  StateMismatchError,
  type AuthContext,
  type BlobStore,
  type PutBlobOptions,
  type ChangeLogEntry,
  type CommitOptions,
  type IndexKeys,
  type IndexQuery,
  type JmapServerUrls,
  type JsonObject,
  type MetadataStore,
  type MethodContext,
  type MethodDefinition,
  type MethodHandler,
  type PushOptions,
  type PushReport,
  type RequestSummary,
  type StorageAdapter,
  type StoredRecord,
  type VapidKeys,
  type VapidOptions,
  type WriteOp,
} from '@mailless/jmap-engine';
export { generateVapidKeys } from '@mailless/jmap-engine';
export {
  MailRejectedError,
  storedUsage,
  type DeliveryUpdate,
  type IdentityInput,
  type ImportedEmail,
  type ImportOptions,
  type MailEnvelope,
  type MailReceipt,
  type MailTransport,
  type ScheduledSend,
  type ScheduledSendOutcome,
  type SendScheduler,
} from '@mailless/jmap-mail';
